// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpcuokpoumytvtcfgsbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwY3Vva3BvdW15dHZ0Y2Znc2JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNTU2NTcsImV4cCI6MjA1NDkzMTY1N30.OEZOh70gDBJBeCzvcU34w4MRrnCY1qqM1vHzaxjuphU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);